- block:
  - name: apt package manager
    include_role:
      name: apt
    when: ansible_pkg_mgr == "apt"
  - name: yum package manager
    include_role:
      name: yum
    when: ansible_pkg_mgr == "yum"
  when: ansible_facts|list
